image: python:3.6-alpine

stages:
  - test
  - publish

variables:
  PIP_CACHE_DIR: vendor/pip

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - "$PIP_CACHE_DIR"

.setup: &setup
  before_script:
    - apk add --no-cache g++ libffi libffi-dev libstdc++ make openssl openssl-dev
    - LDFLAGS=-L/lib make install

test:
  stage: test
  <<: *setup
  script: make test

.publish: &publish
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker pull "$CI_REGISTRY_IMAGE:$IMAGE_TAG" || true
    - docker build --cache-from "$CI_REGISTRY_IMAGE:$IMAGE_TAG" -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE"

publish-branch:
  stage: publish
  <<: *publish
  variables:
    IMAGE_TAG: "$CI_COMMIT_REF_NAME"
  only:
    - master
    - develop
    - gitlab-migration

publish-tag:
  stage: publish
  <<: *publish
  variables:
    IMAGE_TAG: "$CI_COMMIT_TAG"
  only:
    - tags
